version: '3.8'

services:
  backend:
    build: .
    restart: always
    command: gunicorn --bind 0.0.0.0:5001 --log-level debug app:app
    env_file: .env
    ports:
      - "5001:5001"

networks:
  default:
    name: starfall-network
    external: true