version: '3.8'

services:
  backend:
    build: .
    restart: always
    command: gunicorn --bind 0.0.0.0:5001 --log-level debug app:app
    env_file: .env
    volumes:
      - ./static/:./static/
    ports:
      - "5001:5001"

networks:
  default:
    name: nick-network
    external: true